DELETE FROM AIRLINEHASPLANE; 
DELETE FROM RESERVES;
DELETE FROM FLIGHTPILOT;
DELETE FROM PILOTS;
DELETE FROM FLIGHTSTAFF;
DELETE FROM STAFF;
DELETE FROM FLIGHTS;
DELETE FROM CUSTOMEREMAIL;
DELETE FROM CUSTOMERPHONE;
DELETE FROM CUSTOMERFAX;
DELETE FROM CUSTOMERS;
DELETE FROM SEATS;
DELETE FROM PLANETYPE;
DELETE FROM PLANECAPACITY;
DELETE FROM AIRLINES;
DELETE FROM AIRPORTS;
DELETE FROM CITIES;

commit;




	


