DROP SEQUENCE CITIES_SEQ;
DROP SEQUENCE PLANETYPE_SEQ;
DROP SEQUENCE CUSTOMERS_SEQ;
DROP SEQUENCE FLIGHTS_SEQ;
DROP SEQUENCE RESERVES_SEQ;
DROP SEQUENCE PILOTS_SEQ;
DROP SEQUENCE STAFF_SEQ;

DROP TABLE AIRLINEHASPLANE; 
DROP TABLE RESERVES;

DROP TABLE FLIGHTPILOT;
DROP TABLE PILOTS;
DROP TABLE FLIGHTSTAFF;
DROP TABLE STAFF;
DROP TABLE FLIGHTS;

DROP TABLE CUSTOMEREMAIL;
DROP TABLE CUSTOMERPHONE;
DROP TABLE CUSTOMERFAX;
DROP TABLE CUSTOMERS;

DROP TABLE SEATS;
DROP TABLE PLANETYPE;
DROP TABLE PLANECAPACITY;

DROP TABLE AIRLINES;
DROP TABLE AIRPORTS;
DROP TABLE CITIES;

commit;




	


